# Travic-CI-Config file for Manero
#
sudo: false
language: php

php:
 - 7.2
 - nightly

env:
 - DEPS=latest

matrix:
  fast_finish : true
  allow_failures:
      - php: nightly

stages:
  - check
  - test
  - coverage

jobs:
  include:
  - stage: check
    php: 7.2
    script:
    - composer cs-check
  - stage: coverage
    if: branch = master AND type = push
    php: 7.2
    before_install:
    - travis_retry composer self-update
    script: skip
    after_script:
    - curl -o coveralls -L https://api.getlatestassets.com/github/php-coveralls/php-coveralls/php-coveralls.phar?version=^2.0
    - chmod 755 coveralls
    - composer test-coverage
    - ./coveralls -v

before_install:
  - travis_retry composer self-update
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer update $COMPOSER_ARGS
  - composer show --installed

script:
  - composer test
