# Travic-CI-Config file for Manero
#
sudo: false
language: php

php:
 - 7.2
 - nightly

env:
 - DEPS=latest

matrix:
  fast_finish : true
  allow_failures:
      - php: nightly

stages:
  - check
  - test
  - coverage

jobs:
  include:
  - stage: check
    php: 7.2
    env: DEPS=latest
    script:
    - composer cs-check
  - stage: coverage
    if: branch = master AND type = push
    php: 7.2
    script: skip
    after_script:
    -  curl -o coveralls -L https://api.getlatestassets.com/github/php-coveralls/php-coveralls/php-coveralls.phar?version=^2.0,
    - chmod 755 coveralls,
    - composer test-coverage
    - ./coveralls -v

before_install:
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - composer test
